[package]
name = "tensordb"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
jni = "0.21.1"
lazy_static = "1.4.0"
ndarray = "0.15.3"
serde = "1.0.217"
serde_json = "1.0.138"
tch = "0.4.0"

[lib]
name="tensorlib"
crate-type = ["cdylib"]
